/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROG_H_RPCGEN
#define _PROG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXLEN 1024

typedef char *filename;

struct request {
	filename name;
	int start;
};
typedef struct request request;


typedef char filechunk[MAXLEN];

struct chunkreceive {
	filechunk data;
	int bytes;
};
typedef struct chunkreceive chunkreceive;


struct chunksend {
	filename name;
	filechunk data;
	int bytes;
};
typedef struct chunksend chunksend;


struct readfile_res {
	int errno;
	union {
		chunkreceive chunk;
	} readfile_res_u;
};
typedef struct readfile_res readfile_res;

struct intpair {
	int a;
	int b;
};
typedef struct intpair intpair;

typedef struct {
	u_int String_len;
	char *String_val;
} String;

#define MATHPROG 0x20000008
#define MATHVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_1(intpair *, CLIENT *);
extern  int * add_1_svc(intpair *, struct svc_req *);
#define SUB 2
extern  int * sub_1(intpair *, CLIENT *);
extern  int * sub_1_svc(intpair *, struct svc_req *);
#define SENDSTRING 3
extern  String * sendstring_1(void *, CLIENT *);
extern  String * sendstring_1_svc(void *, struct svc_req *);
#define SENDSTRINGS 4
extern  String * sendstrings_1(String *, CLIENT *);
extern  String * sendstrings_1_svc(String *, struct svc_req *);
#define retrievefile 5
extern  readfile_res * retrievefile_1(request *, CLIENT *);
extern  readfile_res * retrievefile_1_svc(request *, struct svc_req *);
#define sendfile 6
extern  String * sendfile_1(chunksend *, CLIENT *);
extern  String * sendfile_1_svc(chunksend *, struct svc_req *);
extern int mathprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_1();
extern  int * add_1_svc();
#define SUB 2
extern  int * sub_1();
extern  int * sub_1_svc();
#define SENDSTRING 3
extern  String * sendstring_1();
extern  String * sendstring_1_svc();
#define SENDSTRINGS 4
extern  String * sendstrings_1();
extern  String * sendstrings_1_svc();
#define retrievefile 5
extern  readfile_res * retrievefile_1();
extern  readfile_res * retrievefile_1_svc();
#define sendfile 6
extern  String * sendfile_1();
extern  String * sendfile_1_svc();
extern int mathprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_filename (XDR *, filename*);
extern  bool_t xdr_request (XDR *, request*);
extern  bool_t xdr_request (XDR *, request*);
extern  bool_t xdr_filechunk (XDR *, filechunk);
extern  bool_t xdr_chunkreceive (XDR *, chunkreceive*);
extern  bool_t xdr_chunkreceive (XDR *, chunkreceive*);
extern  bool_t xdr_chunksend (XDR *, chunksend*);
extern  bool_t xdr_chunksend (XDR *, chunksend*);
extern  bool_t xdr_readfile_res (XDR *, readfile_res*);
extern  bool_t xdr_intpair (XDR *, intpair*);
extern  bool_t xdr_String (XDR *, String*);

#else /* K&R C */
extern bool_t xdr_filename ();
extern bool_t xdr_request ();
extern bool_t xdr_request ();
extern bool_t xdr_filechunk ();
extern bool_t xdr_chunkreceive ();
extern bool_t xdr_chunkreceive ();
extern bool_t xdr_chunksend ();
extern bool_t xdr_chunksend ();
extern bool_t xdr_readfile_res ();
extern bool_t xdr_intpair ();
extern bool_t xdr_String ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROG_H_RPCGEN */
